### ISSUE TITLE
F6 conflicting with Section Jumping shortcut

### ISSUE THREAD

**Issue by studiobutter** [thewilloftheshadow/QuickToggle#2]
Hello, I like the shortcuts for toggling on and off plugins and themes but the Plugin is conflict with Discord Default F6 shortcut which is section jumping. Recording provided below

https://user-images.githubusercontent.com/55838591/227241679-a97dcba1-eb9d-4e45-8348-074971295295.mp4

I suggest changing the key to F7 and F8 or adding a way for user to customize the shortcut key

**Comment by thewilloftheshadow** [comment]
Interesting, F6 doesn't do that for me on Mac, so it must be a Windows thing. I can make them customizable in the next update that I've been working on
